<?php
require_once __DIR__ . '/admin_common.php';
$PID = (int)($_GET['PID'] ?? $_GET['pid'] ?? 0);
$product = $controller->getProductByID($PID);
if (!$product) { admin_header('Product Not Found', 'products'); echo '<div class="card" style="padding:20px">Product not found. PID = '.h($PID).'</div>'; admin_footer(); exit; }
$variants = $controller->getProductVariants($PID);
admin_header('Edit Product #' . $PID, 'products');
?>
<div class="alert err" id="err"></div><div class="alert ok" id="ok"></div>
<div class="form-box"><h2 style="margin-bottom:12px">Main Product Data</h2><form id="baseForm"><input type="hidden" name="PID" value="<?= (int)$PID ?>"><div class="grid"><div class="group"><label>Name</label><input name="name" value="<?= h($product['name'] ?? '') ?>"></div><div class="group"><label>Category</label><select name="category" id="cat" onchange="showType()"><option value="Bag" <?= ($product['category'] ?? '') === 'Bag' ? 'selected' : '' ?>>Bag</option><option value="Clog" <?= ($product['category'] ?? '') === 'Clog' ? 'selected' : '' ?>>Clog</option><option value="Slipper" <?= ($product['category'] ?? '') === 'Slipper' ? 'selected' : '' ?>>Slipper</option></select></div><div class="group"><label>Base Price</label><input type="number" step="0.01" name="price" value="<?= h($product['price'] ?? 0) ?>"></div><div class="group"><label>Branch ID</label><input type="number" name="BranchID" value="<?= h($product['BranchID'] ?? 0) ?>"></div><div class="group full"><label>Description</label><textarea name="description" rows="3"><?= h($product['descriptions'] ?? '') ?></textarea></div></div>
<div id="type-Bag" class="type"><div class="grid"><div class="group"><label>Capacity Liters</label><input name="capacityLiters" type="number" value="<?= h($product['capacityLiters'] ?? 0) ?>"></div><div class="group"><label>Number of Pockets</label><input name="numpackets" type="number" value="<?= h($product['numpackets'] ?? 0) ?>"></div></div></div><div id="type-Clog" class="type"><div class="grid"><div class="group"><label>Heel Height</label><input name="heelHeight" type="number" step="0.1" value="<?= h($product['heelHeight'] ?? 0) ?>"></div><div class="group"><label>Strap Type</label><input name="strapType" value="<?= h($product['strapType'] ?? '') ?>"></div></div></div><div id="type-Slipper" class="type"><div class="grid"><div class="group"><label>Material Softness</label><input name="materialsoftness" value="<?= h($product['materialsoftness'] ?? '') ?>"></div></div></div><button type="button" class="btn btn-rose" onclick="saveBase()">Save Main Product</button></form></div>
<div class="form-box"><h2 style="margin-bottom:12px">Add New Variant</h2><form id="variantForm" enctype="multipart/form-data"><input type="hidden" name="PID" value="<?= (int)$PID ?>"><div class="grid"><div class="group"><label>Color</label><input name="color" placeholder="Pink"></div><div class="group"><label>Size</label><input name="size" type="number" placeholder="38"></div><div class="group"><label>Stock</label><input name="stock" type="number" min="0" placeholder="20"></div><div class="group"><label>Extra Price</label><input name="add_price" type="number" step="0.01" placeholder="0.00"></div><div class="group full"><label>Image</label><input type="file" name="image_file" accept="image/*"></div></div><button type="button" class="btn btn-rose" onclick="addVariant()">Add Variant</button></form></div>
<div class="card"><div class="card-head"><div class="card-title">Current Variants</div></div><table><thead><tr><th>Variant Data</th></tr></thead><tbody><?php if($variants): foreach($variants as $v): $pvid=(int)($v['pvid'] ?? 0); $imgs=$controller->getVariantImages($pvid); ?><tr><td><form class="variantEdit" enctype="multipart/form-data"><input type="hidden" name="pvid" value="<?= $pvid ?>"><div class="grid"><div class="group"><label>Color</label><input name="color" value="<?= h($v['color'] ?? '') ?>"></div><div class="group"><label>Size</label><input name="size" type="number" value="<?= (int)($v['sizes'] ?? 0) ?>"></div><div class="group"><label>Stock</label><input name="stock" type="number" value="<?= (int)($v['stock'] ?? 0) ?>"></div><div class="group"><label>Extra Price</label><input name="add_price" type="number" step="0.01" value="<?= h($v['add_price'] ?? 0) ?>"></div><div class="group full"><label>Add Image</label><input type="file" name="image_file" accept="image/*"></div></div><div class="image-grid" style="margin:6px 0 12px"><?php if($imgs): foreach($imgs as $im): $piid=(int)($im['piid'] ?? $im['id'] ?? 0); ?><div class="image-box"><img src="<?= h(admin_img_url($im['images'] ?? '')) ?>" class="thumb" alt="Product image"><button type="button" class="btn btn-danger" onclick="deleteImage(<?= $piid ?>)">Delete Image</button></div><?php endforeach; else: ?><span class="muted">No images.</span><?php endif; ?></div><button type="button" class="btn btn-warning" onclick="saveVariant(this.form)">Save Variant</button><button type="button" class="btn btn-danger" onclick="deleteVariant(<?= $pvid ?>)">Delete Variant</button></form></td></tr><?php endforeach; else: ?><tr><td style="text-align:center;color:var(--muted)">No variants.</td></tr><?php endif; ?></tbody></table></div>
<script>
function m(id,text){const e=document.getElementById(id);e.textContent=text||'';e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}
function showType(){document.querySelectorAll('.type').forEach(x=>x.style.display='none');const box=document.getElementById('type-'+document.getElementById('cat').value);if(box)box.style.display='block'}showType();
function saveBase(){fetch(APP_BASE+'/MVC/Controller/AdminController.php?action=updateProduct',{method:'POST',body:new FormData(document.getElementById('baseForm'))}).then(r=>r.json()).then(r=>{m(r.success?'ok':'err',r.message || (r.success?'Product updated.':'Failed to update product.'));if(r.success)setTimeout(()=>location.reload(),800)}).catch(()=>m('err','Connection error.'))}
function addVariant(){fetch(APP_BASE+'/MVC/Controller/AdminController.php?action=addProductVariant',{method:'POST',body:new FormData(document.getElementById('variantForm'))}).then(r=>r.json()).then(r=>{m(r.success?'ok':'err',r.message || (r.success?'Variant added.':'Failed to add variant.'));if(r.success)setTimeout(()=>location.reload(),800)}).catch(()=>m('err','Connection error.'))}
function saveVariant(form){fetch(APP_BASE+'/MVC/Controller/AdminController.php?action=updateProductVariant',{method:'POST',body:new FormData(form)}).then(r=>r.json()).then(r=>{m(r.success?'ok':'err',r.message || (r.success?'Variant updated.':'Failed to update variant.'));if(r.success)setTimeout(()=>location.reload(),800)}).catch(()=>m('err','Connection error.'))}
function deleteVariant(pvid){if(!confirm('Delete this variant? Its images will be deleted too.'))return;post('deleteProductVariant',{pvid}).then(r=>{toast(r.message || (r.success?'Variant deleted.':'Failed to delete variant.'));if(r.success)setTimeout(()=>location.reload(),700)})}
function deleteImage(piid){if(!confirm('Delete this image?'))return;post('deleteProductImage',{piid}).then(r=>{toast(r.message || (r.success?'Image deleted.':'Failed to delete image.'));if(r.success)setTimeout(()=>location.reload(),700)})}
</script>
<?php admin_footer(); ?>
